import ValidationGlobal from "@/components/validation/ValidationGlobal";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ValidationGlobal />
      <body>{children}</body>
    </html>
  );
}
