
import { ReactNode } from 'react'
import './../../styles/globals2.css'
import  Sidebar  from '@/components/sidebar/Sidebar'
import { font } from './font'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}


export default function RootLayout ({
  children
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="header"></header>
        <Sidebar />
        {children}
      </body>
    </html>
  )
}