import { ReactNode } from 'react';
import { Box, Paper, CssBaseline } from '@mui/material';
import { styled } from '@mui/system';
import Sidebar from '@/components/sidebarOwner/Sidebar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const Background = styled(Paper)(({ theme }) => ({
  background: 'linear-gradient(to bottom right, #000000, #FF0000)',
  color: 'white',
  minHeight: '100vh',
  position: 'relative',
}));

const GranulatedOverlay = styled('div')(({ theme }) => ({
  content: '""',
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundImage: 'url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABCAYAAAD5PA/NAAAAIklEQVR42mP8/8+AARlBN3dKiRoxoAAAAASUVORK5CYII=)',
  opacity: 0.2,
  zIndex: 1,
}));

export default function RootLayout({
  children
}: {
  children: ReactNode
}) {
  return (
    <Box sx={{ display: 'flex' }}>
      <CssBaseline />
      <Sidebar />
      <Box component="main" sx={{ flexGrow: 1, overflow: 'hidden' }}>
        <Background>
          <Box sx={{ overflowY: 'scroll', height: '100vh', position: 'relative' }}>
            <GranulatedOverlay />
            {children}
          </Box>
        </Background>
      </Box>
    </Box>
  );
}































