import { ReactNode } from 'react'
import { Paper } from '@mui/material';
import Sidebar from '@/components/sidebarOwner/Sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: ReactNode
}) {
  const backgroundStyles = {
    background: 'linear-gradient(to bottom right, #000000, #FF0000)',
    color: 'white',
    minHeight: '100vh',
  };

  return (
    <html lang="en">
      <head>
        <style>{`
          body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
          }
        `}</style>
      </head>
      <body>
        <Paper style={backgroundStyles}>
          <Sidebar />
          {children}
        </Paper>
      </body>
    </html>
  )
}

































