export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import AlertButton from "@/components/client/AlertButton";
import Footer from "@/components/client/Footer";
import Header from "@/components/client/TopBar";
import Validation from "@/components/client/Validation";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Validation />
      <body>
        <AlertButton />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
